# Simple Python Calculator
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
print("\nCalculator Results")
print("Addition:", num1 + num2)
print("Subtraction:", num1 - num2)
print("Multiplication:", num1 * num2)
print("Division:", num1 / num2)
print("Modulus:", num1 % num2)
print("Exponent:", num1 ** num2)